### ISSUE TITLE
Unable to build with qt5 5.15.2

### ISSUE THREAD

**Issue by shalzz** [open-eid/DigiDoc4-Client#912]
Will trying to build the latest release with `qt5` version `5.15.2` I get the following error:
```
/home/shalzz/.cache/pacaur/qdigidoc4/src/client/widgets/CheckBox.cpp: In member function ‘virtual void CheckBox::paintEvent(QPaintEvent*)’:
/home/shalzz/.cache/pacaur/qdigidoc4/src/client/widgets/CheckBox.cpp:48:29: error: variable ‘QPainterPath path’ has initializer but incomplete type
   48 |   QPainterPath path(QPointF(rect.left(), rect.center().y()));
      |                             ^~~~
make[2]: *** [client/CMakeFiles/qdigidoc4.dir/build.make:1022: client/CMakeFiles/qdigidoc4.dir/widgets/CheckBox.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:369: client/CMakeFiles/qdigidoc4.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
```

OS: Arch Linux

**Comment by smirnov** [comment]
I've submitted a PR. If you want to fix the build without waiting for next upstream release: feel free to use the patch that I've done for Fedora: https://src.fedoraproject.org/rpms/qdigidoc/blob/fcbaae479434a5e7678e9806fcddf2c1b917ab70/f/qt5.15.patch
